export interface Product {
  id: string;
  name: string;
  model: string;
  image: string;
  category: string;
  description: string;
  specs: Record<string, string>;
  features: string[];
  datasheet?: string;
  applications?: string[];
  compliance?: string[];
}

export const products: Product[] = [
  {
    id: '1.6t-osfp-dr8',
    name: '1.6T OSFP DR8',
    model: 'LO1600-DR8M2C-L',
    image: '/images/1. 1.6T OSFP DR8 (LO1600-DR8M2C).jpg',
    category: '1.6T / 800G High-Speed',
    datasheet: '/datasheets/1. OSFP 1.6TBASE-DR8 Optical Transceiver(LO1600-DR8M2C).pdf',
    description: 'The Fly Global Trading Limited LO1600-DR8M2C-L is a high-performance 1.6T OSFP DR8 optical transceiver, designed for next-generation AI clusters, hyperscale data centers, and 1.6T Ethernet interconnects. It complies with IEEE 802.3dj and OSFP MSA standards and integrates 8 full-duplex PAM4 channels, each operating at 200 Gb/s, delivering an aggregate bandwidth of 1.6 Tb/s over up to 500 m of single-mode fiber. Built-in digital diagnostics and CMIS management ensure reliable operation in demanding environments.',
    specs: {
      'Form Factor': 'OSFP',
      'Data Rate': '1.6 Tb/s (8 × 200 Gb/s PAM4)',
      'Wavelength': '1310 nm',
      'Reach': '500 m (Single-Mode Fiber)',
      'Connector': 'Dual MPO-12 APC',
      'Power Consumption': '< 12 W',
      'Case Temperature': '0°C to 70°C',
      'Voltage': '3.3 V',
      'Baud Rate': '106.25 GBd',
    },
    features: [
      'Hot-pluggable OSFP form factor',
      '8 full-duplex electrical and optical lanes',
      'Double MPO-12 APC optical interface',
      'Single 3.3V power supply',
      'Maximum power consumption: < 12 W',
      'Supports transmission up to 500 m over SMF',
      'Compatible with IEEE 802.3dj 1.6TAUI-8 and 1.6TBASE-DR8',
      'Built-in digital diagnostics (DDM) via 2-wire interface',
      'CMIS 5.2 management interface',
      'RoHS compliant',
    ],
    applications: [
      '2 × 800G DR4 applications with FEC',
      '8 × 200GbE breakout applications',
      'AI/HPC clusters',
      'InfiniBand XDR interconnect',
      'Hyperscale data centers',
    ],
    compliance: [
      'IEEE 802.3dj 1.6TAUI-8',
      'IEEE 802.3dj 1.6TBASE-DR8',
      'OSFP MSA',
      'CMIS 5.2',
      'RoHS',
    ]
  },
  {
    id: '800g-osfp-sr8',
    name: '800G OSFP SR8',
    model: 'LO800-SR8M2C',
    image: '/images/2. 800G OSFP SR8 (LO800-SR8M2C).jpg',
    category: '1.6T / 800G High-Speed',
    datasheet: '/datasheets/2. OSFP 800GBASE-SR8 Optical Transceiver(LO800-SR8M2C).pdf',
    description: 'The Fly Global Trading Limited LO800-SR8M2C is a high-performance 800G OSFP SR8 optical transceiver, designed for hyperscale data centers, AI/ML clusters, and next-generation 800G Ethernet links. Compliant with IEEE 802.3db, IEEE 802.3ck, and OSFP MSA, this module integrates 8 full-duplex PAM4 channels, each operating at 100 Gb/s, delivering a total bandwidth of 800 Gb/s over 50 m OM4 multimode fiber. With low power consumption and built-in digital diagnostics, it delivers reliable high-speed performance for short-reach connectivity.',
    specs: {
      'Form Factor': 'OSFP',
      'Data Rate': '800 Gb/s (8 × 100 Gb/s PAM4)',
      'Wavelength': '850 nm (SR)',
      'Reach': '50 m (OM4) / 30 m (OM3)',
      'Connector': 'Double MPO-12 APC',
      'Power Consumption': '< 14 W',
      'Case Temperature': '0°C to 70°C',
      'Voltage': '3.3 V',
      'Baud Rate': '53.125 GBd',
    },
    features: [
      'Hot-pluggable OSFP module',
      'Double MPO-12 APC receptacle',
      '8-lane full-duplex transceiver',
      'Maximum power consumption: < 14 W',
      '8 × 100 Gb/s 850 nm VCSEL-based transmitters',
      'Supports up to 50 m OM4 / 30 m OM3',
      'Built-in digital diagnostics (DDM)',
      'I²C management interface',
    ],
    applications: [
      '2 × 400G SR4 with FEC',
      '8 × 100GbE breakout',
      'AI/ML GPU clusters',
      'InfiniBand NDR',
      'Data center short-reach interconnect',
    ],
    compliance: [
      'IEEE 802.3db 800GAUI-8',
      'IEEE 802.3ck 800GBASE-SR8',
      'CMIS 5.0',
      'OSFP MSA',
      'RoHS',
    ]
  },
  {
    id: '800g-osfp-dr8',
    name: '800G OSFP DR8',
    model: 'LO800-DR8M2C',
    image: '/images/3. 800G OSFP DR8 (LO800-DR8M2C).jpg',
    category: '1.6T / 800G High-Speed',
    datasheet: '/datasheets/3. OSFP 800GBASE-DR8 Optical Transceiver(LO800-DR8M2C).pdf',
    description: 'The Fly Global Trading Limited LO800-DR8M2C is a high-performance 800G OSFP DR8 optical transceiver, purpose-built for long-reach 800G Ethernet interconnects in hyperscale data centers and AI/HPC clusters. Compliant with IEEE 802.3bs, IEEE 802.3ck, and OSFP MSA, this module integrates 8 full-duplex PAM4 channels, each operating at 100 Gb/s. The transceiver delivers an aggregate bandwidth of 800 Gb/s over up to 500 m of single-mode fiber. With robust digital diagnostics and 3.3 V low-power operation, the LO800-DR8M2C ensures reliable performance for next-generation optical links.',
    specs: {
      'Form Factor': 'OSFP',
      'Data Rate': '800 Gb/s (8 × 100 Gb/s PAM4)',
      'Wavelength': '1310 nm (DR8)',
      'Reach': '500 m (Single-Mode Fiber)',
      'Connector': 'Double MPO-12 APC',
      'Power Consumption': '< 14 W',
      'Case Temperature': '0°C to 70°C',
      'Voltage': '3.3 V',
      'Baud Rate': '53.125 GBd',
    },
    features: [
      'Hot-pluggable OSFP form factor',
      'Double MPO-12 APC receptacle',
      '8-lane full-duplex PAM4 transceiver',
      'Maximum power consumption: < 14 W',
      'Supports transmission distances up to 500 m over SMF',
      'Built-in digital diagnostics via 2-wire interface',
      'I²C management interface',
    ],
    applications: [
      '2 × 400G DR4 with FEC',
      '8 × 100GbE breakout',
      'InfiniBand NDR',
      'AI/ML GPU clusters',
      'Hyperscale data center long-reach optical links',
    ],
    compliance: [
      'IEEE 802.3bs 800GAUI-8',
      'IEEE 802.3ck 800GBASE-DR8',
      'OSFP MSA',
      'CMIS 5.0',
      'RoHS',
    ]
  },
  {
    id: '400g-qsfp112-vr4',
    name: '400G QSFP112 VR4',
    model: 'LQ400-VR4MC',
    image: '/images/4. 400G QSFP112 VR4 (LQ400-VR4MC).jpg',
    category: '400G / 200G Data Center',
    datasheet: '/datasheets/4. QSFP112 400GBASE-VR4 Optical Transceiver(LQ400-VR4MC).pdf',
    description: 'The Fly Global Trading Limited LQ400-VR4MC is a high-performance 400G QSFP112 VR4 optical transceiver, designed for short-reach 400G Ethernet connections in modern data centers. The module complies with IEEE 802.3bs, IEEE 802.3df, and QSFP112 MSA, integrating 4 full-duplex PAM4 channels, each transmitting at 100 Gb/s to deliver an aggregate bandwidth of 400 Gb/s over 50 m OM4/OM5 multimode fiber. With ultra-low power consumption and built-in digital diagnostics, it is ideal for high-density 400G deployments.',
    specs: {
      'Form Factor': 'QSFP112',
      'Data Rate': '400 Gb/s (4 × 100 Gb/s PAM4)',
      'Wavelength': '850 nm (VR4)',
      'Reach': '50 m (OM4 / OM5)',
      'Connector': 'Single MPO-12 APC',
      'Power Consumption': '< 2.4 W',
      'Case Temperature': '0°C to 70°C',
      'Voltage': '3.3 V',
      'Baud Rate': '53.125 GBd',
    },
    features: [
      'Hot-pluggable QSFP112 form factor',
      '4-lane full-duplex PAM4 transceiver',
      'Designed for short-reach multimode links (OM4 / OM5)',
      'Maximum power consumption: < 2.4 W',
      '4 × 100G 850 nm VCSEL-based transmitters',
      'Built-in digital diagnostics via 2-wire serial interface',
      'I²C management interface',
    ],
    applications: [
      '400GBASE-VR4 Ethernet',
      'High-density data center interconnects',
      'TOR/Switch-to-Server links',
      'Short-reach 400G aggregation networks',
    ],
    compliance: [
      'IEEE 802.3bs 400GAUI-4',
      'IEEE 802.3df 400GBASE-VR4',
      'QSFP112 MSA',
      'CMIS 4.0',
      'RoHS',
    ]
  },
  {
    id: '400g-qsfp112-dr4',
    name: '400G QSFP112 DR4',
    model: 'LQ400-DR4MC',
    image: '/images/5. 400G QSFP112 DR4 (LQ400-DR4MC).jpg',
    category: '400G / 200G Data Center',
    datasheet: '/datasheets/5. QSFP112 400GBASE-DR4 Optical Transceiver(LQ400-DR4MC).pdf',
    description: 'The Fly Global Trading Limited LQ400-DR4MC is a high-performance 400G QSFP112 DR4 optical transceiver, purpose-built for long-reach 400G Ethernet and next-generation data center interconnects. Compliant with IEEE 802.3-2022 400GBASE-DR4, OIF-CEI-5.0, and QSFP112 MSA (SFF-8665), this module integrates 4 full-duplex PAM4 channels, each delivering 100 Gb/s, for an aggregate bandwidth of 400 Gb/s over up to 500 m of single-mode fiber. With advanced power efficiency, built-in digital diagnostics, and robust signal integrity, it is ideal for high-density deployments in AI/HPC clusters and hyperscale data centers.',
    specs: {
      'Form Factor': 'QSFP112',
      'Data Rate': '400 Gb/s (4 × 100 Gb/s PAM4)',
      'Wavelength': '1310 nm (DR4)',
      'Reach': '500 m (Single-Mode Fiber)',
      'Connector': 'Single MPO-12 APC',
      'Power Consumption': '< 9 W',
      'Case Temperature': '0°C to 70°C',
      'Voltage': '3.3 V',
      'Baud Rate': '53.125 GBd',
    },
    features: [
      'Hot-pluggable QSFP112 form factor',
      '4-lane full-duplex PAM4 transceiver',
      'Transmission distance up to 500 m SMF',
      'Maximum power consumption: < 9 W',
      'Built-in digital diagnostics (DDM)',
      'I²C management interface',
    ],
    applications: [
      '400GBASE-DR4 Ethernet',
      'InfiniBand NDR',
      'Data center spine-leaf interconnect',
      'AI/ML GPU cluster networking',
      'High-capacity SMF data center links',
    ],
    compliance: [
      'IEEE 802.3-2022 400GBASE-DR4',
      'OIF-CEI-5.0',
      'QSFP112 MSA',
      'CMIS 5.2',
      'RoHS',
    ]
  },
  {
    id: '400g-osfp-rhs-sr4',
    name: '400G OSFP-RHS SR4',
    model: 'LOR400-SR4MC',
    image: '/images/6. 400G OSFP-RHS SR4 (LOR400-SR4MC).jpg',
    category: '400G / 200G Data Center',
    datasheet: '/datasheets/6. OSFP-RHS 400GBASE-SR4 Optical Transceiver(LOR400-SR4MC).pdf',
    description: 'The Fly Global Trading Limited LOR400-SR4MC is a high-performance 400G OSFP-RHS SR4 optical transceiver, designed for short-reach 400G Ethernet links in high-density data center environments. Compliant with IEEE 802.3db, IEEE 802.3ck, and OSFP MSA, the module integrates 4 full-duplex PAM4 channels, each operating at 100 Gb/s, delivering a combined bandwidth of 400 Gb/s over up to 100 m OM4 multimode fiber. With its compact RHS thermal design, low-latency VCSEL optics, and integrated digital diagnostics, it delivers efficient and reliable performance for AI/ML clusters and next-generation data center deployments.',
    specs: {
      'Form Factor': 'OSFP-RHS',
      'Data Rate': '400 Gb/s (4 × 100 Gb/s PAM4)',
      'Wavelength': '850 nm (SR4)',
      'Reach': '100 m (OM4 fiber)',
      'Connector': 'Single MPO-12',
      'Power Consumption': '< 8 W',
      'Case Temperature': '0°C to 70°C',
      'Voltage': '3.3 V',
      'Baud Rate': '53.125 GBd',
    },
    features: [
      'Hot-pluggable OSFP-RHS module',
      '4-lane full-duplex PAM4 optical transceiver',
      'Supports up to 100 m OM4 short-reach applications',
      'Maximum power consumption: < 8 W',
      '4 × 100G 850 nm VCSEL-based transmitters',
      'Built-in digital diagnostics monitoring (DDM)',
      'I²C management interface',
    ],
    applications: [
      '400GBASE-SR4 Ethernet',
      'High-density data center top-of-rack connectivity',
      'AI/ML GPU cluster networking',
      'Short-reach multimode aggregation networks',
      'InfiniBand NDR (short-reach)',
    ],
    compliance: [
      'IEEE 802.3db 400GAUI-4',
      'IEEE 802.3ck 400GBASE-SR4',
      'OSFP MSA',
      'CMIS 5.0',
      'RoHS',
    ]
  },
  {
    id: '400g-osfp-rhs-dr4',
    name: '400G OSFP-RHS DR4',
    model: 'LOR400-DR4MC',
    image: '/images/7. 400G OSFP-RHS DR4 (LOR400-DR4MC).jpg',
    category: '400G / 200G Data Center',
    datasheet: '/datasheets/7. OSFP-RHS 400GBASE-DR4 Optical Transceiver(LOR400-DR4MC).pdf',
    description: 'The Fly Global Trading Limited LOR400-DR4MC is a high-performance 400G OSFP-RHS DR4 optical transceiver, designed for long-reach 400G Ethernet, AI/ML clusters, and hyperscale data center interconnects. Compliant with IEEE 802.3bs, IEEE 802.3ck, and OSFP MSA, the module integrates 4 independent PAM4 transmit and receive channels, each operating at 100 Gb/s, providing an aggregate throughput of 400 Gb/s over up to 500 m single-mode fiber. With its robust OSFP-RHS thermal design, low power consumption, and complete digital diagnostics, the LOR400-DR4MC is built for demanding modern networking environments.',
    specs: {
      'Form Factor': 'OSFP-RHS',
      'Data Rate': '400 Gb/s (4 × 100 Gb/s PAM4)',
      'Wavelength': '1310 nm (DR4)',
      'Reach': '500 m (Single-Mode Fiber)',
      'Connector': 'Single MPO-12 APC',
      'Power Consumption': '< 9 W',
      'Case Temperature': '0°C to 70°C',
      'Voltage': '3.3 V',
      'Baud Rate': '53.125 GBd',
    },
    features: [
      'Hot-pluggable OSFP-RHS transceiver',
      '4-lane full-duplex PAM4 signaling',
      'Supports transmission up to 500 m SMF',
      'Maximum power consumption: < 9 W',
      '4 × 100 Gb/s PAM4 SIP modulator transmitters',
      'Built-in digital diagnostics (DDM)',
      'I²C management interface',
    ],
    applications: [
      '400GBASE-DR4 Ethernet',
      'AI/ML GPU clusters (long-reach fabric)',
      'Data center spine-leaf connectivity',
      'InfiniBand NDR (long-reach)',
      'Cloud & hyperscale SMF backbone links',
    ],
    compliance: [
      'IEEE 802.3bs 400GAUI-8',
      'IEEE 802.3ck 400GBASE-DR4',
      'OSFP MSA V5.0',
      'CMIS 5.2',
      'RoHS',
    ]
  },
  {
    id: '200g-qsfp56-sr4',
    name: '200G QSFP56 SR4',
    model: 'LQ200-SR4MC',
    image: '/images/8. 200G QSFP56 SR4 (LQ200-SR4MC).jpg',
    category: '400G / 200G Data Center',
    datasheet: '/datasheets/8. QSFP56 200GBASE-SR4 Optical Transceiver(LQ200-SR4MC).pdf',
    description: 'The Fly Global Trading Limited LQ200-SR4MC is a high-performance 200G QSFP56 SR4 optical transceiver, designed for short-reach 200G Ethernet links and modern data center applications. Compliant with IEEE 802.3bs, IEEE 802.3cd, QSFP56 MSA (SFF-8665), and CMIS 4.0/SFF-8636, the module integrates 4 full-duplex channels, each operating at 50 Gb/s, delivering a total bandwidth of 200 Gb/s over up to 100 m OM4 multimode fiber. With extremely low power consumption and 850 nm VCSEL optics, the LQ200-SR4MC is optimized for cost-effective, high-density, short-reach deployments.',
    specs: {
      'Form Factor': 'QSFP56',
      'Data Rate': '200 Gb/s (4 × 50 Gb/s PAM4)',
      'Wavelength': '850 nm (SR4)',
      'Reach': '70 m (OM3) / 100 m (OM4)',
      'Connector': 'Single MPO-12 / APC',
      'Power Consumption': '< 2.5 W',
      'Case Temperature': '0°C to 70°C',
      'Voltage': '3.3 V',
      'Baud Rate': '26.5625 GBd',
    },
    features: [
      'Hot-pluggable QSFP56 transceiver',
      '4 full-duplex optical lanes',
      'Supports up to 100 m OM4 short-reach fiber',
      'Maximum power consumption: < 2.5 W',
      '4 × 53G 850 nm VCSEL transmitters',
      'Built-in digital diagnostic functions',
      'I²C management interface',
    ],
    applications: [
      '200GBASE-SR4 Ethernet',
      'Short-reach data center interconnect',
      'Top-of-Rack (ToR) switching',
      'InfiniBand HDR',
      'GPU cluster and server connectivity',
    ],
    compliance: [
      'IEEE 802.3bs 200GAUI-4',
      'IEEE 802.3cd 200GBASE-SR4',
      'QSFP56 MSA SFF-8665',
      'CMIS 4.0 / SFF-8636',
      'RoHS',
    ]
  },
];
